spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: always
    schema: schema.sql
    data: data.sql

  messages:
    basename: bundle

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

  h2:
    console:
      path: /h2-console
      enabled: true

locale: ru

logging:
  level:
    ROOT: ERROR

