DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID    BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (ID),
    GENRE_ID BIGINT REFERENCES GENRES (ID),
    PRIMARY KEY (ID)
);
