GET http://localhost:8080/book?page=0&size=3
###
DELETE http://localhost:8080/book/5f77f464c90ea356e4b46978
###
DELETE http://localhost:8080/book
###
POST http://localhost:8080/book
Content-Type: application/json

{
  "name": "New book2",
  "authors": [
    "Unknown",
    "Lermontov"
  ],
  "genres": [
    "Tragedy",
    "Roman"
  ]

}
