version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - nw
  mongo:
    image: mongo:latest
    networks:
      - nw
networks:
  nw: